### ISSUE TITLE
inconsistent results in the paper

### ISSUE THREAD

**Issue by hhr114** [coleygroup/Graph2SMILES#1]
Hi,

Would u plz explain why the performance of GraphRetro [1] in Table 3 of your paper is much lower than that of the original workshop paper [1]?
I further notice that one of the authors of Graph2SMILES is the author of GraphRetro.

[1] "Learning graph models for template-free retrosynthe". ICML Workshop, 2020

![image.png](https://ae05.alicdn.com/kf/H4eef8a1cecf44e01915452f2eea452261.png)
![image.png](https://ae02.alicdn.com/kf/Hc0d2020f62cb48d782298244b18232d42.png)

**Comment by connorcoley** [comment]
The first version of GraphRetro suffered from an information leak described well by RetroXpert (https://github.com/uta-smile/RetroXpert). The encoder was unfortunately not made perfectly insensitive to atom ordering at that time. The updated GraphRetro article has the correct results now.

**Comment by WYejian** [comment]
The model throws the error "RuntimeError: CUDA error: device-side assertion fired" when I run reaction prediction, not when I run retrosynthesis
