### ISSUE TITLE
reaction prediction

### ISSUE THREAD

**Issue by YejianW** [coleygroup/Graph2SMILES#2]
The model throws the error "RuntimeError: CUDA error: device-side assertion fired" (graph2seq_series_rel.py
,line 125, in forward,  memory_lengths=memory_lengths) when I run reaction prediction, not when I run retrosynthesis.

**Comment by DeepMindAGI** [comment]
I also have this problem. Have you solved it

**Comment by zhengkaitu** [comment]
@WYejian  @zpking Can you try to see whether the problem can be resolved by setting REL_BUCKETS to 11 in train_g2s.sh? CUDA device-side assertion typically points to the case when the lookup index is greater than what the embedding table contains.

**Comment by DeepMindAGI** [comment]
@zhengkaitu Thank you very much. The problem has been solved
