### ISSUE TITLE
Why pad `a_graph` and `b_graph` to length 11?

### ISSUE THREAD

**Issue by yippp** [coleygroup/Graph2SMILES#3]
I am interested in your work. While I read the code, I found that during preprocessing, in the class `get_graph_features_from_smi` in `data_utils.py`.
The codes
```
    # padding
    for a_graph in a_graphs:
        while len(a_graph) < 11:            # OH MY GOODNESS... Fe can be bonded to 10...
            a_graph.append(1e9)

    for b_graph in b_graphs:
        while len(b_graph) < 11:            # OH MY GOODNESS... Fe can be bonded to 10...
            b_graph.append(1e9)
```
I cannot understand why the atom and bond graphs needed to be padded to length 11. Could you tell me something about it? 
Thanks a lot.

**Comment by wzpneau** [comment]
Excuse me, I encountered a problem when I was training with a model. Have you ever encountered this problem?

RuntimeError: CUDA error: device-side assert triggered

**Comment by zhengkaitu** [comment]
@yippp As in the comment, during our own testing with cornor cases, we found some metal complexes can literally have up to 10 bonds (e.g. for Fe centers bonded to 10 ligands). Therefore we decided to pad to 11 just to be more robust.
