### ISSUE TITLE
Large data, configuration?

### ISSUE THREAD

**Issue by vthost** [coleygroup/Graph2SMILES#5]
Hi,
I tried to train the model on ~230k reactions, but within 24hrs it reached only 1.3k steps. This seems a bit too few, therefore I wonder if I am missing some parameters or other detail. Also, how many steps you would suggest to train to get decent results?

Apart from this, the setup and scripts run pretty smoothly!

**Comment by zhengkaitu** [comment]
This is a bit too slow (almost like CPU speed). Were you training on GPU and what's your system config? There could be some compatibility issue that forced the code to resort to CPU on some latest GPUs (e.g. 3090). This sort of warnings/issues wouldn't have been captured by the log so you might need to look at some console log.

For the steps, what we observe is that with the default setting the performance started to flatten after 200k steps. Note though in general the more steps the better (e.g. 1-2 points increase for another 200k steps), as shown by several previous works.
