### ISSUE TITLE
About the parameters of train_g2s.sh for USPTO-Full

### ISSUE THREAD

**Issue by bbn2h** [coleygroup/Graph2SMILES#9]
Hi, 
I've encountered a problem that I tried to use your code to train a model on our dataset of about 2M reactions, but the result seemed a little poor. So I want to ask for your train_g2s.sh code (especially the parameters) of Full dataset, as it will be more suitable for our attempt to train on large dataset.
Thank you!

**Comment by zhengkaitu** [comment]
Please refer to the [SI](https://pubs.acs.org/doi/10.1021/acs.jcim.2c00321#_i44) of the paper. The hyperparameter settings can be found in Section S3.

Also, we have had new repositories for Graph2SMILES as part of ASKCOSv2. Please refer to https://gitlab.com/mlpds_mit/askcosv2/retro/graph2smiles for serving/retraining if for the retro direction. It does require docker and includes a bunch of enhancement and bug fixes.

**Comment by bbn2h** [comment]
I see. Thanks a lot!
